# This file was generated by the {rix} R package v0.14.3 on 2025-01-14
# with following call:
# >rix(r_ver = "4.3.3",
#  > date = NULL,
#  > r_pkgs = c("data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "renv",
#  > NULL),
#  > system_pkgs = c("adwaita-qt",
#  > NULL),
#  > ide = "rstudio",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2024-02-29.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      data_table
      dplyr
      ggplot2
      renv;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      adwaita-qt
      glibcLocales
      nix
      R;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [  rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages  wrapped_pkgs ];
  
}
