# This file was generated by the {rix} R package v0.13.4 on 2024-11-29
# with following call:
# >rix(r_ver = "019f5c29c5afeb215587e17bf1ec31dc1913595b",
#  > r_pkgs = c("data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "renv",
#  > NULL),
#  > system_pkgs = c("adwaita-qt",
#  > NULL),
#  > git_pkgs = list(list(package_name = "colorout",
#  > repo_url = "https://github.com/jalvesaq/colorout/",
#  > commit = "6eca95213c6cb2fae1c2c4eaccf43de4c93a65b5"),
#  > list(package_name = "duckdb",
#  > repo_url = "https://github.com/duckdb/duckdb-r/",
#  > commit = "71c71a6b824bd0f2c0fca43c5dfa53645b17bfb7")),
#  > ide = "rstudio",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  >      print = TRUE)
# It uses nixpkgs' revision 019f5c29c5afeb215587e17bf1ec31dc1913595b for reproducibility purposes
# which will install R version 4.3.3.
# Report any issues to https://github.com/ropensci/rix

let
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/019f5c29c5afeb215587e17bf1ec31dc1913595b.tar.gz") {};

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      data_table
      dplyr
      ggplot2
      rlang
      renv;
  };

  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "colorout";
      src = pkgs.fetchgit {
        url = "https://github.com/jalvesaq/colorout/";
        rev = "6eca95213c6cb2fae1c2c4eaccf43de4c93a65b5";
        sha256 = "sha256-HBQRKqyYYAKJj2TFXBgX5Gc6EnkMG3ZaMCxuHVR9Cfc=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    })

# 19864453f7d0ed095256d848b46e7b8630989bac

    (pkgs.rPackages.buildRPackage {
      name = "duckdb";
      version = "1.1.2";
      src = pkgs.fetchgit {
        url = "https://github.com/duckdb/duckdb-r/";
        rev = "71c71a6b824bd0f2c0fca43c5dfa53645b17bfb7";
        sha256 = "sha256-oNrRa0OebsHiUkYl5yDZnpVG+Du5Zhx3fH69vbaRwtk=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          DBI;
      };
    })
   ];

  system_packages = builtins.attrValues {
    inherit (pkgs)
      adwaita-qt
      glibcLocales
      nix
      R;
  };

  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG           = "en_US.UTF-8";
  LC_ALL         = "en_US.UTF-8";
  LC_TIME        = "en_US.UTF-8";
  LC_MONETARY    = "en_US.UTF-8";
  LC_PAPER       = "en_US.UTF-8";
  LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages  wrapped_pkgs ];

  shellHook = ''
    ## for rstudio GUI
    export QT_XCB_GL_INTEGRATION=none
    ## check for dependencies
    Rscript -e "renv::update(check=TRUE)"
  '';
}
