# This file was generated by the {rix} R package v0.14.3 on 2025-01-14
# with following call:
# >rix(r_ver = "4.3.3",
#  > date = NULL,
#  > r_pkgs = c("data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "renv",
#  > NULL),
#  > system_pkgs = c("adwaita-qt",
#  > NULL),
#  > ide = "rstudio",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE)

let

 ## Nix repo for R 4.3.3
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2024-02-29.tar.gz") {};

  ## R packages
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      data_table
      dplyr
      ggplot2
      janitor
      knitr
      plotly
      readODS
      renv
      ;
  };

  ## System packages
  system_packages = builtins.attrValues {
    inherit (pkgs)
      adwaita-qt
      glibcLocales
      nix
      R;
  };

  ## R packages from github
  git_archive_pkgs = [

   (pkgs.rPackages.buildRPackage {
      name = "colorout";
      src = pkgs.fetchgit {
        url    = "https://github.com/jalvesaq/colorout/";
        rev    = "2a5f21496162ea30684d2783e3a204f4756db4e8";
        sha256 = "sha256-RglnS3QS85598qC87uciW/d64mgeavUDccdXt+GKwFM=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    })

   ];

  ## Feed Rstudio with this environment packages
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs ];
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs  rpkgs  system_packages  wrapped_pkgs ];

  shellHook = ''
    ## for rstudio GUI
    export QT_XCB_GL_INTEGRATION=none
    alias rstudio='setsid rstudio &'
    ## check for dependencies
    Rscript -e "renv::update(check=TRUE)"
    echo "Show recomendation"
  '';
}
